/* USER related */
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

/* JOBS related */
export const FETCH_JOBS = "FETCH_JOBS";
export const RECIEVE_JOBS = "RECIEVE_JOBS";
export const FILTERED_JOBS = "FILTERED_JOBS";

/* ORGANIZATIONS related */
export const UNIQUE_ORGANIZATIONS = "UNIQUE_ORGANIZATIONS";
export const ADD_SELECTED_ORGANIZATIONS = "ADD_SELECTED_ORGANIZATIONS";
export const INCLUDE_JOB_BY_ORGANIZATION = "INCLUDE_JOB_BY_ORGANIZATION";

/* JOB TYPES related */
export const ADD_SELECTED_JOB_TYPES = "ADD_SELECTED_JOB_TYPES";
export const UNIQUE_JOB_TYPES = "UNIQUE_JOB_TYPES";
export const INCLUDE_JOB_BY_JOB_TYPE = "INCLUDE_JOB_BY_JOB_TYPE";

/* DEGREES related */
export const RECIEVE_DEGREES = "RECIEVE_DEGREES";
export const FETCH_DEGREES = "FETCH_DEGREES";
export const UNIQUE_DEGREES = "UNIQUE_DEGREES";
export const INCLUDE_JOB_BY_DEGREE = "INCLUDE_JOB_BY_DEGREE";
export const ADD_SELECTED_DEGREES = "ADD_SELECTED_DEGREES";

export const CLEAR_FILTERS = "CLEAR_FILTERS";
